apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: dkkahm/node-backend-example2
          env:
            - name: CONTENTS_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/contents
              name: backend-contents
      volumes:
        - name: backend-contents
          persistentVolumeClaim:
            claimName: host-pvc
