apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/dkkam/Projects/study/study-docker-and-kubernetes/004.kubernetes-volume/data
    type: DirectoryOrCreate