apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    group: example  
spec:
  selector:
    app: node-backend-pod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: LoadBalancer